# Generated by Django 5.2.5 on 2025-10-06 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='Income', max_length=10),
            preserve_default=False,
        ),
    ]
