# Generated by Django 5.2.5 on 2025-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Expense', 'expense'), ('Income', 'income')], default=False, max_length=10),
        ),
    ]
