# Generated by Django 5.2.5 on 2025-10-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_category_type_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
