# Generated by Django 5.2.5 on 2025-10-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
    ]
