# Generated by Django 5.2.5 on 2025-10-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_budget_end_date_remove_budget_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='transactions',
        ),
    ]
