# Generated by Django 5.2.5 on 2025-10-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pots'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.pots'),
        ),
    ]
