# Generated by Django 5.2.5 on 2025-09-02 18:58

import backend.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expencetrackeruser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expencetrackeruser',
            managers=[
                ('objects', backend.accounts.models.ExpenceTrackerUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='expencetrackeruser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='expencetrackeruser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
