name: Deploy Django to Azure Web App

on:
  push:
    branches:
      - main  # или твоята основна бранш

env:
  AZURE_WEBAPP_NAME: expence # името на твоя Web App в Azure
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Събиране на статичните файлове
      - name: Collect static
        run: |
          cd backend && python manage.py collectstatic --noinput

     

      # Деплой в Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .


